name: search
on:
  push:
    paths:
      - 'search/**'
      - 'test_search.py'
  pull_request:
    paths:
      - 'search/**'
      - 'test_search.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run tests
      run: |
        python test_search.py
